# Site settings
title: Spectator Web
email: web@stuyspec.com
description: > # this means to ignore newlines until "baseurl:"
  Information for members of the Web Department of the Stuyvesant Spectator
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: stuyspec

# Build settings
markdown: kramdown
